# - include: a10_virtual_server
- hosts: localhost
  tasks:
    - a10_service_group:
        host: "10.48.6.222"
        username: admin
        password: a10
        partition: shared
        state: "present"
        name: sg-81-tcp
        protocol: "tcp"
        lb_method: "round-robin"
        members:
          - name: foo1.mydomain.com
            port: 8081
            state: enable
